import networkx as nx
import matplotlib.pyplot as plt
import textdistance
import spacy
import globals 

nlp = spacy.load('en_core_web_sm', disable=['parser','ner'])

def number_of_lemmas(words, blank_array):
    irregular_words = {
        "person":["people"],
        "person":["people"],
        "ox":["oxen"],
        "oxen":["ox"],
        "man":["men"],
        "men":["man"],
        "woman":["women"],
        "women":["woman"],
        "caveman":["cavemen"],
        "cavemen":["caveman"],
        "policeman":["policemen"],
        "policemen":["policeman"],
        "child":["children"],
        "children":["child"],
        "foot":["feet"],
        "feet":["foot"],
        "goose":["geese"],
        "geese":["goose"],
        "mouse":["mice"],
        "mice":["mouse"],
        "louse":["lice"],
        "lice":["louse"],
        "penny":["pence"],
        "pence":["penny"],
        "abide":["abided, abode"],
        "abided":["abide", "abode"],
        "abode":["abide","abided"],
        "arise":["arose","arisen"],
        "arose":["arise","arisen"],
        "arisen":["arise","arose"],
        "awake":["awaked","awoke","awoken"],
        "awaked":["awake","awoke","awoken"],
        "awoke":["awake","awaked","awoken"],
        "awoken":["awake","awaked","awoke"],
        "be":["was","were","been"],
        "was":["be","were","been"],
        "were":["be","was","been"],
        "been":["be","were","was"],
        "bear":["bore","born"],
        "bore":["bear","born"],
        "born":["bear","bore"],
        "beat":["beaten"],
        "beaten":["beat"],
        "become":["became"],
        "became":["become"],
        "befall": ["befell", "befallen"],
        "befell":["befall","befallen"],
        "befallen":["befall","befell"],
        "beget":["begot","begotten"],
        "begot":["beget","begotten"],
        "begotten":["begot","beget"],
        "begin":["began","begun"],
        "began":["begin","begun"],
        "begun":["begin","began"],
        "behold":["beheld"],
        "beheld":["behold"],
        "bend":["bent"],
        "bent":["bend"],
        "bereave":["bereft"],
        "bereft":["bereave"],
        "beseech":["besought"],
        "besought":["beseech"],
        "beset":["beset"],
        "bespeak":["bespoke","bespoken"],
        "bespoke":["bespeak","bespoken"],
        "bespoken":["bespeak","bespoke"],
        "bestride":["bestrode","bestridden"],
        "bestrode":["bestride","bestridden"],
        "bestridden":["bestride","bestrode"],
        "bet":["bet"],
        "bid":["bade","bidden"],
        "bade":["bid","bidden"],
        "bidden":["bade","bid"],
        "bind":["bound"],
        "bound":["bind"],
        "bite":["bit", "bitten"],
        "bit":["bite","bitten"],
        "bitten":["bite","bit"],
        "bleed":["bled"],
        "bled":["bleed"],
        "blow":["blew","blown"],
        "blew":["blow","blown"],
        "blown":["blew","blow"],
        "break":["broke","broken"],
        "broke":["break","broken"],
        "broken":["break","broke"],
        "breed":["bred"],
        "bred":["breed"],
        "bring":["brought"],
        "brought":["bring"],
        "broadcasted":["broadcast"],
        "broadcast":["broadcasted"],
        "build":["built"],
        "built":["build"],
        "burst":["burst"],
        "burn":["burnt","burned"],
        "burnt":["burn","burned"],
        "burned":["burn","burnt"],
        "buy":["bought"],
        "bought":["buy"],
        "can":["could"],
        "could":["can"],
        "catch":["caught"],
        "caught":["catch"],
        "choose":["chose", "chosen"],
        "chose":["choose","chosen"],
        "chosen":["choose","chose"],
        "cling":["clung"],
        "clung":["cling"],
        "come":["came"],
        "came":["come"],
        "creep":["crept"],
        "crept":["creep"],
        "deal":["dealt"],
        "dealt":["deal"],
        "dig":["dug"],
        "dug":["dig"],
        "do":["did, done"],
        "did":["do","done"],
        "done":["do","did"],
        "draw":["drew","drawn"],
        "drawn":["draw","drew"],
        "drew":["draw","drawn"],
        "dream":["dreamed","dreamt"],
        "dreamed":["dream","dreamt"],
        "dreamt":["dreamed","dream"],
        "drink":["drank","drunk"],
        "drank":["drink","drunk"],
        "drunk":["drink","drank"],
        "drive":["drove","driven"],
        "drove":["drive","driven"],
        "driven":["drive","drove"],
        "dwell":["dwelled","dwelt"],
        "dwelled":["dwell","dwelt"],
        "dwelt":["dwell","dwelled"],
        "eat":["eaten","ate"],
        "eaten":["eat","ate"],
        "ate":["eaten","eat"],
        "interweave":["interwoven"],
        "interwoven":["interweave"],
        "fall":["fell","fallen"],
        "fell":["fall","fallen"],
        "fallen":["fell","fall"],
        "feed":["fed"],
        "fed":["feed"],
        "feel":["felt"],
        "felt":["feel"],
        "fight":["fought"],
        "fought":["fight"],
        "find":["found"],
        "found":["find"],
        "flee":["fled"],
        "fled":["flee"],
        "fling":["flung"],
        "flung":["fling"],
        "fly":["flew","flown"],
        "flew":["fly","flown"],
        "flown":["fly","flew"],
        "forbid":["forbad","forbade","forbidden"],
        "forbad":["forbid","forbade","forbidden"],
        "forbade":["forbid","forbad","forbidden"],
        "forbidden":["forbid","forbad","forbade"],
        "forecast":["forecasted"],
        "forecasted":["forecast"],
        "forget":["forgot","forgotten"],
        "forgot":["forget","forgotten"],
        "forgotten":["forget","forgot"],
        "forgive":["forgave","forgiven"],
        "forgave":["forgive","forgiven"],
        "forgiven":["forgive","forgave"],
        "forsake":["forsaken","forsook"],
        "forsaken":["forsake","forsook"],
        "forsook":["forsake","forsaken"],
        "foresee":["foresaw","foreseen"],
        "foresaw":["foresee","foreseen"],
        "foreseen":["foresaw","foresee"],
        "foretell":["foretold"],
        "foretold":["foretell"],
        "freeze":["froze","frozen"],
        "frozen":["froze","freeze"],
        "froze":["freeze","frozen"],
        "get":["got"],
        "got":["get"],
        "give":["gave","given"],
        "gave":["give","given"],
        "given":["give","gave"],
        "go":["gone","went"],
        "gone":["go","went"],
        "went":["go","gone"],
        "grind":["ground"],
        "ground":["grind"],
        "grow":["grew","grown"],
        "grew":["grow","grown"],
        "grown":["grew","grow"],
        "hang":["hanged","hung"],
        "hung":["hanged","hang"],
        "hanged":["hung","hang"],
        "have":["had"],
        "had":["have"],
        "hear":["heard"],
        "heard":["hear"],
        "hide":["hid","hidden"],
        "hid":["hide","hidden"],
        "hidden":["hid","hide"],
        "hid":["hid"],
        "hold":["held"],
        "held":["hold"],
        "hurt":["hurt"],
        "keep":["kept"],
        "kept":["keep"],
        "kneel":["knelt"],
        "knelt":["kneel"],
        "know":["knew","known"],
        "known":["knew","know"],
        "knew":["know","known"],
        "know":["known","knew"],
        "lay":["laid"],
        "laid":["lay"],
        "lead":["led"],
        "led":["lead"],
        "lean":["leaned","leant"],
        "leaned":["lean","leant"],
        "leant":["lean","leaned"],
        "leap":["leapt"],
        "leapt":["leap"],
        "learn":["learned","learnt"],
        "learnt":["learned","learn"],
        "learned":["learnt","learn"],
        "left":["leave"],
        "leave":["left"],
        "lent":["lend"],
        "lend":["lent"],
        "let":["let"],
        "lie":["lay","lain"],
        "lay":["lie","lain"],
        "lain":["lie","lay"],
        "lose":["lost"],
        "lost":["lose"],
        "make":["made"],
        "made":["make"],
        "mean":["meant"],
        "meant":["mean"],
        "pay":["paid"],
        "paid":["pay"],
        "mistake":["mistook","mistaken"],
        "mistook":["mistake","mistaken"],
        "mistaken":["mistake","mistook"],
        "overhear":["overheard"],
        "overheard":["overhear"],
        "oversleep":["overslept"],
        "overslept":["oversleep"],
        "rend":["rended","rent"],
        "rended":["rend","rent"],
        "rent":["rended","rend"],
        "ride":["rode","ridden"],
        "rode":["ride","ridden"],
        "ridden":["ride","rode"],
        "ring":["rang","rung"],
        "rang":["ring","rung"],
        "rung":["ring","rang"],
        "rise":["rose","risen"],
        "rose":["rise","risen"],
        "risen":["rise","rose"],
        "run":["ran"],
        "ran":["run"],
        "say":["said"],
        "said":["say"],
        "see":["saw","seen"],
        "saw":["see","seen"],
        "seen":["see","saw"],
        "seek":["sought"],
        "sought":["seek"],
        "sell":["sold"],
        "sold":["sell"],
        "shake":["shook","shaken"],
        "shook":["shake","shaken"],
        "shaken":["shook","shake"],
        "shine":["stone"],
        "stone":["shine"],
        "shit":["shat"],
        "shat":["shit"],
        "shoot":["shot"],
        "shot":["shoot"],
        "show":["showed","shown"],
        "showed":["show","shown"],
        "shown":["show","showed"],
        "shrink":["shrank", "shrunk"],
        "shrank":["shrink","shrunk"],
        "shrunk":["shrank","shrunk"],
        "shrive":["shrove","shriven"],
        "shrove":["shrive","shriven"],
        "shrive":["shrove","shriven"],
        "shriven":["shrove","shrive"],
        "sing":["sang","sung"],
        "sang":["sing","sung"],
        "sung":["sing","sang"],
        "sink":["sank", "sunk"],
        "sank":["sink", "sunk"],
        "sunk":["sink","sank"],
        "sit":["sat"],
        "sat":["sit"],
        "slay":["slew","slain"],
        "slew":["slay","slain"],
        "slain":["slay","slew"],
        "sleep":["slept"],
        "slept":["sleep"],
        "slide":["slid"],
        "slid":["slide"],
        "sling":["slung"],
        "slung":["sling"],
        "slink":["slunk"],
        "slunk":["slink"],
        "smell":["smelled","smelt"],
        "smelled":["smell","smelt"],
        "smelt":["smell","smelled"],
        "smite":["smote","smitten"],
        "smote":["smite","smitten"],
        "smitten":["smite","smote"],
        "speak":["spoke","spoken"],
        "spoke":["speak","spoken"],
        "spoken":["speak","spoke"],
        "speed":["speeded","sped"],
        "speeded":["speed","sped"],
        "sped":["speed","speeded"],
        "spin":["spun"],
        "spun":["spin"],
        "spit":["spat"],
        "spat":["spit"],
        "spin":["spun"],
        "spun":["spin"],
        "spoil":["spoiled","spoilt"],
        "spoiled":["spoil","spoilt"],
        "spoilt":["spoiled","spoil"],
        "spring":["sprang","sprung"],
        "sprang":["spring","sprung"],
        "sprung":["spring","sprang"],
        "stand":["stood"],
        "stood":["stand"],
        "steal":["stole","stolen"],
        "stole":["steal","stolen"],
        "stolen":["stole","steal"],
        "stick":["stuck"],
        "stuck":["stick"],
        "sting":["stung"],
        "stung":["sting"],
        "stink":["stank","stunk"],
        "stank":["stink","stunk"],
        "stunk":["stank","stink"],
        "stride":["strode","stridden"],
        "strode":["stride","stridden"],
        "stridden":["stride","strode"],
        "strike":["struck"],
        "struck":["strike"],
        "string":["strung"],
        "strung":["string"],
        "strive":["strove","striven"],
        "strove":["strive","striven"],
        "striven":["strive","strove"],
        "swear":["swore","sworn"],
        "swore":["swear","sworn"],
        "sworn":["swore","swear"],
        "sweep":["swept"],
        "swept":["sweep"],
        "take":["took","taken"],
        "took":["take","taken"],
        "taken":["took","take"],
        "teach":["taught"],
        "taught":["teach"],
        "tear":["tore","torn"],
        "tore":["tear","torn"],
        "torn":["tear","tore"],
        "tell":["told"],
        "told":["tell"],
        "think":["thought"],
        "thought":["think"],
        "throw":["threw","thrown"],
        "threw":["throw","thrown"],
        "thrown":["throw","threw"],
        "tread":["treaded","trod","trodden"],
        "treaded":["tread","trod","trodden"],
        "trod":["treaded","tread","trodden"],
        "trodden":["treaded","trod","tread"],
        "understand":["understood"],
        "understood":["understand"],
        "undertake":["undertook","undertaken"],
        "undertook":["undertake","undertaken"],
        "undertaken":["undertake","undertook"],
        "undo":["undid","undone"],
        "undid":["undo","undone"],
        "undone":["undid","undo"],
        "wake":["woke"],
        "woke":["wake"],
        "wear":["wore","worn"],
        "wore":["wear","worn"],
        "worn":["wear","wore"],
        "weave":["wove","woven"],
        "wove":["weave","woven"],
        "woven":["wove","weave"],
        "weep":["wept"],
        "wept":["weep"],
        "win":["won"],
        "won":["win"],
        "wind":["wound"],
        "wound":["wind"],
        "withdraw":["withdrew","withdrawn"],
        "withdrew":["withdraw","withdrawn"],
        "withdrawn":["withdraw","withdrew"],
        "withstand":["withstood"],
        "withstood":["withstand"],
        "wring":["wrung"],
        "wrung":["wring"],
        "write":["wrote","written"],
        "wrote":["write","written"],
        "written":["write","wrote"]

    }
    for i in range(0, len(words)):
        in_array = False
        word_1_nlp = nlp(words[i].WORD)
        for token in word_1_nlp:
            word_1_lemma = str(token.lemma_).strip()
        
        if word_1_lemma in irregular_words:
            for j in irregular_words[word_1_lemma]:
                if j in blank_array:
                    in_array = True
                    break

            if not in_array:
                blank_array.append(words[i].WORD)

        elif word_1_lemma not in blank_array:
            blank_array.append(words[i].WORD)


            


def create_adjanceylist(words):
    f = open("words.adjlist", "w+")
    g = open("IPA.adjlist", "w+")
    two_character_phonemes = ["oʊ", "ɔɪ", "aɪ", "aʊ"]
    vowels = ["ɑ", "æ", "ə", "ʌ", "ɔ", "a", "aɪ", "aʊ", "ɛ", "e", "ɪ", "i", "o", "ɔ", "ʊ", "u"]
    irregular_words = {
        "person":["people"],
        "person":["people"],
        "ox":["oxen"],
        "oxen":["ox"],
        "man":["men"],
        "men":["man"],
        "woman":["women"],
        "women":["woman"],
        "caveman":["cavemen"],
        "cavemen":["caveman"],
        "policeman":["policemen"],
        "policemen":["policeman"],
        "child":["children"],
        "children":["child"],
        "foot":["feet"],
        "feet":["foot"],
        "goose":["geese"],
        "geese":["goose"],
        "mouse":["mice"],
        "mice":["mouse"],
        "louse":["lice"],
        "lice":["louse"],
        "penny":["pence"],
        "pence":["penny"],
        "abide":["abided, abode"],
        "abided":["abide", "abode"],
        "abode":["abide","abided"],
        "arise":["arose","arisen"],
        "arose":["arise","arisen"],
        "arisen":["arise","arose"],
        "awake":["awaked","awoke","awoken"],
        "awaked":["awake","awoke","awoken"],
        "awoke":["awake","awaked","awoken"],
        "awoken":["awake","awaked","awoke"],
        "be":["was","were","been"],
        "was":["be","were","been"],
        "were":["be","was","been"],
        "been":["be","were","was"],
        "bear":["bore","born"],
        "bore":["bear","born"],
        "born":["bear","bore"],
        "beat":["beaten"],
        "beaten":["beat"],
        "become":["became"],
        "became":["become"],
        "befall": ["befell", "befallen"],
        "befell":["befall","befallen"],
        "befallen":["befall","befell"],
        "beget":["begot","begotten"],
        "begot":["beget","begotten"],
        "begotten":["begot","beget"],
        "begin":["began","begun"],
        "began":["begin","begun"],
        "begun":["begin","began"],
        "behold":["beheld"],
        "beheld":["behold"],
        "bend":["bent"],
        "bent":["bend"],
        "bereave":["bereft"],
        "bereft":["bereave"],
        "beseech":["besought"],
        "besought":["beseech"],
        "beset":["beset"],
        "bespeak":["bespoke","bespoken"],
        "bespoke":["bespeak","bespoken"],
        "bespoken":["bespeak","bespoke"],
        "bestride":["bestrode","bestridden"],
        "bestrode":["bestride","bestridden"],
        "bestridden":["bestride","bestrode"],
        "bet":["bet"],
        "bid":["bade","bidden"],
        "bade":["bid","bidden"],
        "bidden":["bade","bid"],
        "bind":["bound"],
        "bound":["bind"],
        "bite":["bit", "bitten"],
        "bit":["bite","bitten"],
        "bitten":["bite","bit"],
        "bleed":["bled"],
        "bled":["bleed"],
        "blow":["blew","blown"],
        "blew":["blow","blown"],
        "blown":["blew","blow"],
        "break":["broke","broken"],
        "broke":["break","broken"],
        "broken":["break","broke"],
        "breed":["bred"],
        "bred":["breed"],
        "bring":["brought"],
        "brought":["bring"],
        "broadcasted":["broadcast"],
        "broadcast":["broadcasted"],
        "build":["built"],
        "built":["build"],
        "burst":["burst"],
        "burn":["burnt","burned"],
        "burnt":["burn","burned"],
        "burned":["burn","burnt"],
        "buy":["bought"],
        "bought":["buy"],
        "can":["could"],
        "could":["can"],
        "catch":["caught"],
        "caught":["catch"],
        "choose":["chose", "chosen"],
        "chose":["choose","chosen"],
        "chosen":["choose","chose"],
        "cling":["clung"],
        "clung":["cling"],
        "come":["came"],
        "came":["come"],
        "creep":["crept"],
        "crept":["creep"],
        "deal":["dealt"],
        "dealt":["deal"],
        "dig":["dug"],
        "dug":["dig"],
        "do":["did, done"],
        "did":["do","done"],
        "done":["do","did"],
        "draw":["drew","drawn"],
        "drawn":["draw","drew"],
        "drew":["draw","drawn"],
        "dream":["dreamed","dreamt"],
        "dreamed":["dream","dreamt"],
        "dreamt":["dreamed","dream"],
        "drink":["drank","drunk"],
        "drank":["drink","drunk"],
        "drunk":["drink","drank"],
        "drive":["drove","driven"],
        "drove":["drive","driven"],
        "driven":["drive","drove"],
        "dwell":["dwelled","dwelt"],
        "dwelled":["dwell","dwelt"],
        "dwelt":["dwell","dwelled"],
        "eat":["eaten","ate"],
        "eaten":["eat","ate"],
        "ate":["eaten","eat"],
        "interweave":["interwoven"],
        "interwoven":["interweave"],
        "fall":["fell","fallen"],
        "fell":["fall","fallen"],
        "fallen":["fell","fall"],
        "feed":["fed"],
        "fed":["feed"],
        "feel":["felt"],
        "felt":["feel"],
        "fight":["fought"],
        "fought":["fight"],
        "find":["found"],
        "found":["find"],
        "flee":["fled"],
        "fled":["flee"],
        "fling":["flung"],
        "flung":["fling"],
        "fly":["flew","flown"],
        "flew":["fly","flown"],
        "flown":["fly","flew"],
        "forbid":["forbad","forbade","forbidden"],
        "forbad":["forbid","forbade","forbidden"],
        "forbade":["forbid","forbad","forbidden"],
        "forbidden":["forbid","forbad","forbade"],
        "forecast":["forecasted"],
        "forecasted":["forecast"],
        "forget":["forgot","forgotten"],
        "forgot":["forget","forgotten"],
        "forgotten":["forget","forgot"],
        "forgive":["forgave","forgiven"],
        "forgave":["forgive","forgiven"],
        "forgiven":["forgive","forgave"],
        "forsake":["forsaken","forsook"],
        "forsaken":["forsake","forsook"],
        "forsook":["forsake","forsaken"],
        "foresee":["foresaw","foreseen"],
        "foresaw":["foresee","foreseen"],
        "foreseen":["foresaw","foresee"],
        "foretell":["foretold"],
        "foretold":["foretell"],
        "freeze":["froze","frozen"],
        "frozen":["froze","freeze"],
        "froze":["freeze","frozen"],
        "get":["got"],
        "got":["get"],
        "give":["gave","given"],
        "gave":["give","given"],
        "given":["give","gave"],
        "go":["gone","went"],
        "gone":["go","went"],
        "went":["go","gone"],
        "grind":["ground"],
        "ground":["grind"],
        "grow":["grew","grown"],
        "grew":["grow","grown"],
        "grown":["grew","grow"],
        "hang":["hanged","hung"],
        "hung":["hanged","hang"],
        "hanged":["hung","hang"],
        "have":["had"],
        "had":["have"],
        "hear":["heard"],
        "heard":["hear"],
        "hide":["hid","hidden"],
        "hid":["hide","hidden"],
        "hidden":["hid","hide"],
        "hid":["hid"],
        "hold":["held"],
        "held":["hold"],
        "hurt":["hurt"],
        "keep":["kept"],
        "kept":["keep"],
        "kneel":["knelt"],
        "knelt":["kneel"],
        "know":["knew","known"],
        "known":["knew","know"],
        "knew":["know","known"],
        "know":["known","knew"],
        "lay":["laid"],
        "laid":["lay"],
        "lead":["led"],
        "led":["lead"],
        "lean":["leaned","leant"],
        "leaned":["lean","leant"],
        "leant":["lean","leaned"],
        "leap":["leapt"],
        "leapt":["leap"],
        "learn":["learned","learnt"],
        "learnt":["learned","learn"],
        "learned":["learnt","learn"],
        "left":["leave"],
        "leave":["left"],
        "lent":["lend"],
        "lend":["lent"],
        "let":["let"],
        "lie":["lay","lain"],
        "lay":["lie","lain"],
        "lain":["lie","lay"],
        "lose":["lost"],
        "lost":["lose"],
        "make":["made"],
        "made":["make"],
        "mean":["meant"],
        "meant":["mean"],
        "pay":["paid"],
        "paid":["pay"],
        "mistake":["mistook","mistaken"],
        "mistook":["mistake","mistaken"],
        "mistaken":["mistake","mistook"],
        "overhear":["overheard"],
        "overheard":["overhear"],
        "oversleep":["overslept"],
        "overslept":["oversleep"],
        "rend":["rended","rent"],
        "rended":["rend","rent"],
        "rent":["rended","rend"],
        "ride":["rode","ridden"],
        "rode":["ride","ridden"],
        "ridden":["ride","rode"],
        "ring":["rang","rung"],
        "rang":["ring","rung"],
        "rung":["ring","rang"],
        "rise":["rose","risen"],
        "rose":["rise","risen"],
        "risen":["rise","rose"],
        "run":["ran"],
        "ran":["run"],
        "say":["said"],
        "said":["say"],
        "see":["saw","seen"],
        "saw":["see","seen"],
        "seen":["see","saw"],
        "seek":["sought"],
        "sought":["seek"],
        "sell":["sold"],
        "sold":["sell"],
        "shake":["shook","shaken"],
        "shook":["shake","shaken"],
        "shaken":["shook","shake"],
        "shine":["stone"],
        "stone":["shine"],
        "shit":["shat"],
        "shat":["shit"],
        "shoot":["shot"],
        "shot":["shoot"],
        "show":["showed","shown"],
        "showed":["show","shown"],
        "shown":["show","showed"],
        "shrink":["shrank", "shrunk"],
        "shrank":["shrink","shrunk"],
        "shrunk":["shrank","shrunk"],
        "shrive":["shrove","shriven"],
        "shrove":["shrive","shriven"],
        "shrive":["shrove","shriven"],
        "shriven":["shrove","shrive"],
        "sing":["sang","sung"],
        "sang":["sing","sung"],
        "sung":["sing","sang"],
        "sink":["sank", "sunk"],
        "sank":["sink", "sunk"],
        "sunk":["sink","sank"],
        "sit":["sat"],
        "sat":["sit"],
        "slay":["slew","slain"],
        "slew":["slay","slain"],
        "slain":["slay","slew"],
        "sleep":["slept"],
        "slept":["sleep"],
        "slide":["slid"],
        "slid":["slide"],
        "sling":["slung"],
        "slung":["sling"],
        "slink":["slunk"],
        "slunk":["slink"],
        "smell":["smelled","smelt"],
        "smelled":["smell","smelt"],
        "smelt":["smell","smelled"],
        "smite":["smote","smitten"],
        "smote":["smite","smitten"],
        "smitten":["smite","smote"],
        "speak":["spoke","spoken"],
        "spoke":["speak","spoken"],
        "spoken":["speak","spoke"],
        "speed":["speeded","sped"],
        "speeded":["speed","sped"],
        "sped":["speed","speeded"],
        "spin":["spun"],
        "spun":["spin"],
        "spit":["spat"],
        "spat":["spit"],
        "spin":["spun"],
        "spun":["spin"],
        "spoil":["spoiled","spoilt"],
        "spoiled":["spoil","spoilt"],
        "spoilt":["spoiled","spoil"],
        "spring":["sprang","sprung"],
        "sprang":["spring","sprung"],
        "sprung":["spring","sprang"],
        "stand":["stood"],
        "stood":["stand"],
        "steal":["stole","stolen"],
        "stole":["steal","stolen"],
        "stolen":["stole","steal"],
        "stick":["stuck"],
        "stuck":["stick"],
        "sting":["stung"],
        "stung":["sting"],
        "stink":["stank","stunk"],
        "stank":["stink","stunk"],
        "stunk":["stank","stink"],
        "stride":["strode","stridden"],
        "strode":["stride","stridden"],
        "stridden":["stride","strode"],
        "strike":["struck"],
        "struck":["strike"],
        "string":["strung"],
        "strung":["string"],
        "strive":["strove","striven"],
        "strove":["strive","striven"],
        "striven":["strive","strove"],
        "swear":["swore","sworn"],
        "swore":["swear","sworn"],
        "sworn":["swore","swear"],
        "sweep":["swept"],
        "swept":["sweep"],
        "take":["took","taken"],
        "took":["take","taken"],
        "taken":["took","take"],
        "teach":["taught"],
        "taught":["teach"],
        "tear":["tore","torn"],
        "tore":["tear","torn"],
        "torn":["tear","tore"],
        "tell":["told"],
        "told":["tell"],
        "think":["thought"],
        "thought":["think"],
        "throw":["threw","thrown"],
        "threw":["throw","thrown"],
        "thrown":["throw","threw"],
        "tread":["treaded","trod","trodden"],
        "treaded":["tread","trod","trodden"],
        "trod":["treaded","tread","trodden"],
        "trodden":["treaded","trod","tread"],
        "understand":["understood"],
        "understood":["understand"],
        "undertake":["undertook","undertaken"],
        "undertook":["undertake","undertaken"],
        "undertaken":["undertake","undertook"],
        "undo":["undid","undone"],
        "undid":["undo","undone"],
        "undone":["undid","undo"],
        "wake":["woke"],
        "woke":["wake"],
        "wear":["wore","worn"],
        "wore":["wear","worn"],
        "worn":["wear","wore"],
        "weave":["wove","woven"],
        "wove":["weave","woven"],
        "woven":["wove","weave"],
        "weep":["wept"],
        "wept":["weep"],
        "win":["won"],
        "won":["win"],
        "wind":["wound"],
        "wound":["wind"],
        "withdraw":["withdrew","withdrawn"],
        "withdrew":["withdraw","withdrawn"],
        "withdrawn":["withdraw","withdrew"],
        "withstand":["withstood"],
        "withstood":["withstand"],
        "wring":["wrung"],
        "wrung":["wring"],
        "write":["wrote","written"],
        "wrote":["write","written"],
        "written":["write","wrote"]

    }
    # return_string = ""
    # return_string = return_string + words.WORD + " "
    for i in range(0, len(words)):
        word_1 = words[i].IPA_LIST
        word_1_nlp = nlp(words[i].WORD)
        for token in word_1_nlp:
            word_1_lemma = str(token.lemma_).strip()
            f.write(f"{words[i].WORD} ")
            g.write(f"{words[i].IPA} ")
        # print(words.WORD)     
        
        for j in range(0, len(words)):
            if words[i].WORD != words[j].WORD:
                word_2 = words[j].IPA_LIST
                    
                word_2_nlp = nlp(words[j].WORD)
                for token in word_2_nlp:
                    word_2_lemma = str(token.lemma_).strip()

                # Check basic condition first
                if textdistance.levenshtein.distance(word_1, word_2) == 1 and (word_2_lemma != word_1_lemma):
                    # Check if both are irregular
                    if (words[i].WORD not in irregular_words) or (words[j].WORD not in irregular_words):
                        # return_string = return_string + words[j].WORD + " "
                        f.write(f"{words[j].WORD} ")
                        g.write(f"{words[j].IPA} ")

                    # If both irregular then check irregular dictionary
                    elif words[j].WORD not in irregular_words[words.WORD]:
                        # return_string = return_string + words[j].WORD + " "
                        f.write(f"{words[j].WORD} ")
                        g.write(f"{words[j].IPA} ")
                    
    # return_string + return_string + "\n"
        print(words[i].WORD)
    # return return_string

    f.close()
    g.close()

def create_graph():
    graph = nx.read_adjlist('words.adjlist')
    nx.draw(graph,
            with_labels=True,
            node_color='black',
            node_size=18,
            font_size=8,
            verticalalignment='baseline',
            edge_color='grey')
    plt.savefig('graphhhhhhhhhh.png')
    plt.show()


